version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: work-at-olist
    env_file:
      - .env
    volumes:
      - .:/opt/services/workolist/src
      - static_volume:/opt/services/workolist/src/static
      - media_volume:/opt/services/workolist/src/media
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1.15
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/workolist/src/static
      - media_volume:/opt/services/workolist/src/media
    depends_on:
      - web
    networks:
      - nginx_network

  db:
    image: postgres:10
    env_file:
      - .env
    networks:
      - db_network
    volumes:
      - db_volume:/var/lib/postgres/data

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
  static_volume:
  media_volume:
